services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./downloads:/usr/src/app/downloads
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs
      - ./src:/usr/src/app/src
    develop:
      watch:
        - action: rebuild
          path: package.json
