services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./downloads:/usr/src/app/downloads
      - ./data:/usr/src/app/data
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
        - action: rebuild
          path: package.json
